# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name_plural': 'posts'},
        ),
        migrations.AlterModelOptions(
            name='usermeta',
            options={'verbose_name_plural': 'users'},
        ),
        migrations.AddField(
            model_name='usermeta',
            name='work_description',
            field=models.TextField(default='This is a description of my work'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, editable=False),
        ),
    ]
