# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 00:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20170801_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='usermeta',
            name='github',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='usermeta',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='usermeta',
            name='instagram',
            field=models.CharField(max_length=200),
        ),
    ]
