# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 00:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_usermeta_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='external_link',
            field=models.URLField(blank=True),
        ),
    ]
