# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 02:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_post_date'),
    ]

    operations = [

    ]
