# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 17:29
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_auto_20170801_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='category',
            name='meta',
        ),
        migrations.RemoveField(
            model_name='usermeta',
            name='work_description',
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='usermeta',
            name='about',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
