# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 23:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_remove_category_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermeta',
            name='about',
            field=models.TextField(),
        ),
    ]
