# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-05 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_usermeta_about_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermeta',
            name='linkedin',
            field=models.URLField(default='https://www.linkedin.com/in/junyuan-tan-8162a2109/'),
            preserve_default=False,
        ),
    ]
