# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-16 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_auto_20180513_0655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermeta',
            name='about_site',
        ),
        migrations.AddField(
            model_name='usermeta',
            name='for_hire',
            field=models.TextField(default='For Hire'),
            preserve_default=False,
        ),
    ]
