# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-16 13:22
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_auto_20180516_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermeta',
            name='about',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='usermeta',
            name='for_hire',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
